In [125]:
import torch
from torch.utils.data import Dataset,DataLoader,TensorDataset
import torch.nn as nn


In [126]:
words =["This", "book", "was", "fantastic", "I", "really", "love", "science", "fiction", "but", "the", "protagonist", "was", "rude", "sometimes"]

In [127]:
word_to_idx = {word: i for i, word in enumerate(words)}

In [128]:
word_to_idx

{'This': 0,
 'book': 1,
 'was': 12,
 'fantastic': 3,
 'I': 4,
 'really': 5,
 'love': 6,
 'science': 7,
 'fiction': 8,
 'but': 9,
 'the': 10,
 'protagonist': 11,
 'rude': 13,
 'sometimes': 14}

In [129]:
inputs = torch.tensor([word_to_idx[word] for word in words])

In [130]:
inputs

tensor([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [131]:
embedding = nn.Embedding(num_embeddings=len(words),embedding_dim=10)

In [132]:
print(embedding)


Embedding(15, 10)


In [133]:
output = embedding(inputs)

In [134]:
print(output.shape)
print(output[0])

torch.Size([15, 10])
tensor([-0.9175,  0.1808, -0.5805, -0.9813,  1.0255,  0.2556, -0.2636,  0.6221,
        -1.3349, -0.6163], grad_fn=<SelectBackward0>)


In [135]:
paragraph = """Abhishek Waghchaure
Sai Vrundavan, flat no-703, Sr No-56/5B,
Behind Abhiruchi Mall,
Sinhgad road, Vadgaon Bk.,
PUNE, Maharashtra - 411041
Email: abhisw28@gmail.com
Mobile: 8668566528
Dear Human Resources Team
I am excited to apply for the Data Science Engineer position. With a strong academic foundation in
data science and analytics, complemented by practical experience as a software developer, I am
eager to bring my skills to your team and contribute to the innovative AI-driven solutions your
organization is known for.
My M.Tech in Data Science and Analytics has provided me with deep insights into machine
learning, data analysis, and predictive modeling. Although my professional experience at Vinz
Global and Aventior Digital Pvt Ltd primarily involved software development, these roles honed my
technical expertise, particularly in backend development, API improvement, and database
migration. These experiences have given me a solid understanding of the full software development
lifecycle, which is crucial for building and optimizing data pipelines, implementing machine
learning models, and deploying data-driven applications.
One of my significant academic projects involved developing a skin cancer detection and
classification model using convolutional neural networks (CNNs). This project not only enhanced
my machine learning skills but also highlighted the importance of accuracy and innovation in
developing life-impacting solutions. Additionally, my work on a diamond price prediction model
using linear regression demonstrated my ability to analyze complex datasets and create precise,
data-driven forecasts.
I am particularly enthusiastic about this role because it offers the opportunity to transition my strong
technical foundation and passion for data science into a position focused on developing and
optimizing AI solutions. I am eager to collaborate with your multi-functional team, leverage my
problem-solving skills, and contribute to driving the success of your AI-assisted decision-making
processes.
Thank you for considering my application. I am looking forward to the opportunity to discuss how
my background in software development, combined with my academic focus on data science, can
contribute to the innovative projects. Please feel free to contact me at 8668566528 or via email at
abhisw28@gmail.com to schedule an interview.
Sincerely,
Abhishek Waghchaure"""

In [136]:
import nltk
from nltk.corpus import stopwords
import re

In [137]:
def preprocess_text(text):
    corpus = []
    sentences = nltk.sent_tokenize(text)
    for sentence in sentences:
        review = re.sub('[^a-zA-z]', " ", sentence)
        review = review.lower()
        words = nltk.word_tokenize(review)
        processed = [word for word in words if word not in set(stopwords.words("english"))]
        processed_sentences = " ".join(processed)
        corpus.append(processed_sentences)
    return corpus

In [138]:
corpus = preprocess_text(parahagraph)

In [139]:
for sent in corpus:
    words = nltk.word_tokenize(sent)
    for word in words:
        word_to_idx = {word : i for i , word in enumerate(words)}
        inputs = torch.tensor([word_to_idx[word] for word in words])
    embedding = nn.Embedding(num_embeddings=len(words),embedding_dim=10)
    output = embedding(inputs)
        

In [140]:
output

tensor([[ 0.7164,  0.8403, -1.0668,  1.1681,  0.0516, -0.5711,  1.3964, -1.4619,
         -0.9122,  0.7886],
        [-0.2805,  0.0951, -0.0612, -0.2269,  0.8538, -0.5986, -0.4218, -1.0404,
          0.7541, -0.0618],
        [ 1.9585, -0.1569,  1.7823,  0.1100, -1.2229,  1.3297, -0.1190,  0.0184,
         -0.5252,  1.4983]], grad_fn=<EmbeddingBackward0>)

In [151]:
import torch
import torch.nn as nn
import nltk
import re
from nltk.corpus import stopwords

# Preprocess the text
def preprocess_text(text):
    corpus = []
    sentences = nltk.sent_tokenize(text)
    for sentence in sentences:
        review = re.sub('[^a-zA-Z]', " ", sentence)
        review = review.lower()
        words = nltk.word_tokenize(review)
        processed = [word for word in words if word not in set(stopwords.words("english"))]
        processed_sentence = " ".join(processed)
        corpus.append(processed_sentence)
    return corpus


corpus = preprocess_text(paragraph)

# Step 1: Build vocabulary (word to index mapping) for the entire corpus
all_words = [word for sentence in corpus for word in nltk.word_tokenize(sentence)]
word_to_idx = {word: i for i, word in enumerate(set(all_words))}

# Step 2: Convert sentences to sequences of indices
indexed_sentences = [[word_to_idx[word] for word in nltk.word_tokenize(sentence)] for sentence in corpus]

# Step 3: Define the embedding layer
embedding_dim = 10
embedding = nn.Embedding(num_embeddings=len(word_to_idx), embedding_dim=embedding_dim)

# Step 4: Convert indexed sentences to tensors and apply embedding
embedded_sentences = []
for sentence in indexed_sentences:
    inputs = torch.tensor(sentence)  # Convert sentence to tensor
    output = embedding(inputs)  # Apply embedding
    embedded_sentences.append(output)

# Now `embedded_sentences` contains the embedded vectors for each sentence
for i, emb_sentence in enumerate(embedded_sentences):
    print(f"Embedded sentence {i+1}: {emb_sentence}")

Embedded sentence 1: tensor([[ 4.1359e-01, -9.3127e-01,  9.9078e-01,  7.3158e-01, -6.4504e-01,
          3.0031e+00,  2.7077e-01, -1.3190e+00, -2.5058e-01,  1.9909e+00],
        [-7.8162e-01, -1.1957e+00, -6.6741e-01, -7.3805e-01, -1.7215e+00,
          4.4403e-01,  2.5435e-01, -3.8596e-01, -4.8750e-01,  1.1310e+00],
        [-4.5331e-01, -4.8157e-01,  5.7394e-01, -2.2207e+00, -6.4993e-01,
         -3.1225e-01,  1.7106e-01, -6.5593e-01,  5.5915e-01,  1.2136e+00],
        [-9.5653e-01, -3.4757e-01,  1.6594e+00, -9.9075e-01, -1.9534e-01,
          4.1454e-02, -5.0242e-01,  1.4129e+00, -3.2158e-01,  2.2678e-01],
        [ 1.1930e+00,  8.2568e-01, -2.0238e+00, -7.1440e-01, -2.0327e-01,
          1.2014e+00,  6.3158e-01,  2.0822e+00,  1.2114e+00, -1.3617e-01],
        [ 1.1839e+00, -3.4127e-01, -1.2143e-03, -6.9045e-01,  9.6560e-03,
          4.6977e-01,  1.5594e+00, -2.4775e+00, -7.9106e-01, -1.6960e+00],
        [ 3.4047e-01, -1.9253e+00,  4.9490e-01, -3.1017e-01, -1.9429e+00,
          3

In [154]:
print(len(embedded_sentences[1]))
print(len(embedded_sentences[3]))
print(len(embedded_sentences[5]))

22
24
16
