In [724]:
import torch
from torchvision

In [725]:
import torch.torch_version


torch.torch_version

<module 'torch.torch_version' from '/opt/anaconda3/envs/tensor/lib/python3.10/site-packages/torch/torch_version.py'>

In [726]:
type(torch)

module

In [727]:
lst = [[1,2,3],[4,5,6]]
tensor = torch.tensor(lst)

In [728]:
tensor.device

device(type='cpu')

In [729]:
import torch.nn as nn  ## Has various sequential models like ANN,Linear,CNN,RNN,LSTM,GRU
import torch.nn.functional as F ## for one hot encoding
import numpy
import torch.nn
import torch.optim as optim ## optimizers 
from torch.utils.data import DataLoader, Dataset
import pandas as pd


In [730]:
df = pd.read_csv('/Users/abhishekwaghchaure/Desktop/PWSkillsDataScience/DataSets/winequality-red.csv')

In [731]:
df.head()
print(df.shape)
print(df.size)

(1599, 12)
19188


In [732]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [733]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [734]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [735]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [736]:
from sklearn.model_selection import train_test_split

In [737]:
features = df.drop('quality',axis=1)

In [738]:
target = df['quality']

In [739]:
print(target.shape)
print(features.shape)

(1599,)
(1599, 11)


In [740]:
X_train,X_test, y_train,y_test = train_test_split(features,target,test_size=0.20,random_state=32)

In [741]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(1279, 11)
(1279,)
(320, 11)
(320,)


In [742]:
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F

In [743]:
y_train.max().item()

8

In [744]:
train_dataset_features = torch.tensor(X_train.to_numpy())
train_dataset_targets = torch.tensor(y_train.to_numpy())

## One hot Encoding for targets
train_dataset_targets =F.one_hot(train_dataset_targets, num_classes=9)

training_data = TensorDataset(train_dataset_features,train_dataset_targets)
print(training_data)

next(iter(training_data))

(tensor([ 9.6000,  0.5400,  0.4200,  2.4000,  0.0810, 25.0000, 52.0000,  0.9970,
          3.2000,  0.7100, 11.4000], dtype=torch.float64),
 tensor([0, 0, 0, 0, 0, 0, 1, 0, 0]))

In [745]:
test_dataset_features = torch.tensor(X_test.to_numpy())
test_dataset_targets = torch.tensor(y_test.to_numpy())

## One Hot Encoding for test Targets
test_dataset_targets = F.one_hot(test_dataset_targets, num_classes=9)

testing_data = TensorDataset(test_dataset_features,test_dataset_targets)

In [746]:
print(train_dataset_features.shape)
print(train_dataset_targets.shape)
print(test_dataset_features.shape)
print(test_dataset_targets.shape)

torch.Size([1279, 11])
torch.Size([1279, 9])
torch.Size([320, 11])
torch.Size([320, 9])


In [747]:
dataloader = DataLoader(training_data,batch_size=32,shuffle=True)

In [748]:
for features, label in dataloader:
    print(features, label)

tensor([[6.5000e+00, 4.0000e-01, 1.0000e-01, 2.0000e+00, 7.6000e-02, 3.0000e+01,
         4.7000e+01, 9.9554e-01, 3.3600e+00, 4.8000e-01, 9.4000e+00],
        [1.0400e+01, 4.1000e-01, 5.5000e-01, 3.2000e+00, 7.6000e-02, 2.2000e+01,
         5.4000e+01, 9.9960e-01, 3.1500e+00, 8.9000e-01, 9.9000e+00],
        [5.9000e+00, 4.4000e-01, 0.0000e+00, 1.6000e+00, 4.2000e-02, 3.0000e+00,
         1.1000e+01, 9.9440e-01, 3.4800e+00, 8.5000e-01, 1.1700e+01],
        [9.6000e+00, 3.2000e-01, 4.7000e-01, 1.4000e+00, 5.6000e-02, 9.0000e+00,
         2.4000e+01, 9.9695e-01, 3.2200e+00, 8.2000e-01, 1.0300e+01],
        [7.2000e+00, 2.5000e-01, 3.7000e-01, 2.5000e+00, 6.3000e-02, 1.1000e+01,
         4.1000e+01, 9.9439e-01, 3.5200e+00, 8.0000e-01, 1.2400e+01],
        [7.7000e+00, 9.6500e-01, 1.0000e-01, 2.1000e+00, 1.1200e-01, 1.1000e+01,
         2.2000e+01, 9.9630e-01, 3.2600e+00, 5.0000e-01, 9.5000e+00],
        [8.5000e+00, 6.5500e-01, 4.9000e-01, 6.1000e+00, 1.2200e-01, 3.4000e+01,
         1.51

tensor([[6.6000e+00, 6.3000e-01, 0.0000e+00, 4.3000e+00, 9.3000e-02, 5.1000e+01,
         7.7500e+01, 9.9558e-01, 3.2000e+00, 4.5000e-01, 9.5000e+00],
        [8.2000e+00, 7.3000e-01, 2.1000e-01, 1.7000e+00, 7.4000e-02, 5.0000e+00,
         1.3000e+01, 9.9680e-01, 3.2000e+00, 5.2000e-01, 9.5000e+00],
        [7.5000e+00, 6.0000e-01, 3.0000e-02, 1.8000e+00, 9.5000e-02, 2.5000e+01,
         9.9000e+01, 9.9500e-01, 3.3500e+00, 5.4000e-01, 1.0100e+01],
        [7.3000e+00, 3.6500e-01, 4.9000e-01, 2.5000e+00, 8.8000e-02, 3.9000e+01,
         1.0600e+02, 9.9660e-01, 3.3600e+00, 7.8000e-01, 1.1000e+01],
        [1.0000e+01, 3.5000e-01, 4.7000e-01, 2.0000e+00, 6.1000e-02, 6.0000e+00,
         1.1000e+01, 9.9585e-01, 3.2300e+00, 5.2000e-01, 1.2000e+01],
        [8.9000e+00, 5.0000e-01, 2.1000e-01, 2.2000e+00, 8.8000e-02, 2.1000e+01,
         3.9000e+01, 9.9692e-01, 3.3300e+00, 8.3000e-01, 1.1100e+01],
        [7.5000e+00, 5.2000e-01, 4.2000e-01, 2.3000e+00, 8.7000e-02, 8.0000e+00,
         3.80

In [765]:
next(iter(dataloader))

[tensor([[9.2000e+00, 3.1000e-01, 3.6000e-01, 2.2000e+00, 7.9000e-02, 1.1000e+01,
          3.1000e+01, 9.9615e-01, 3.3300e+00, 8.6000e-01, 1.2000e+01],
         [8.3000e+00, 2.6000e-01, 4.2000e-01, 2.0000e+00, 8.0000e-02, 1.1000e+01,
          2.7000e+01, 9.9740e-01, 3.2100e+00, 8.0000e-01, 9.4000e+00],
         [1.2600e+01, 4.1000e-01, 5.4000e-01, 2.8000e+00, 1.0300e-01, 1.9000e+01,
          4.1000e+01, 9.9939e-01, 3.2100e+00, 7.6000e-01, 1.1300e+01],
         [8.3000e+00, 6.1500e-01, 2.2000e-01, 2.6000e+00, 8.7000e-02, 6.0000e+00,
          1.9000e+01, 9.9820e-01, 3.2600e+00, 6.1000e-01, 9.3000e+00],
         [1.0300e+01, 3.4000e-01, 5.2000e-01, 2.8000e+00, 1.5900e-01, 1.5000e+01,
          7.5000e+01, 9.9980e-01, 3.1800e+00, 6.4000e-01, 9.4000e+00],
         [7.4000e+00, 5.3000e-01, 1.2000e-01, 1.9000e+00, 1.6500e-01, 4.0000e+00,
          1.2000e+01, 9.9702e-01, 3.2600e+00, 8.6000e-01, 9.2000e+00],
         [8.2000e+00, 3.2000e-01, 4.2000e-01, 2.3000e+00, 9.8000e-02, 3.0000e+00,


In [749]:
# model = nn.Sequential(
#     nn.Linear(11,30),
#     nn.Linear(30,12),
#     nn.Linear(12,9),
#     nn.Sigmoid()
# )

In [750]:
class model(nn.Module):
    def __init__(self):
        super(model,self).__init__()
        self.fc1 = nn.Linear(11,30)
        self.fc2 = nn.Linear(30,12)
        self.fc3 = nn.Linear(12,9)
        
    def forward(self,x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.softmax(self.fc3(x))
        return x
        

In [751]:
model = model()

In [753]:
from torch.optim import SGD


In [754]:
criterian = nn.CrossEntropyLoss()
optimizer = SGD(model.parameters(),lr =0.96)

In [755]:
model.parameters

<bound method Module.parameters of model(
  (fc1): Linear(in_features=11, out_features=30, bias=True)
  (fc2): Linear(in_features=30, out_features=12, bias=True)
  (fc3): Linear(in_features=12, out_features=9, bias=True)
)>

In [756]:
## training Loop
for features, labels in dataloader:
    for epoch in range(11):
        optimizer.zero_grad()
        output = model(features.float())
        loss = criterian(output,labels.float())
        loss.backward()
        optimizer.step()
        
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 2.1889524459838867
Epoch 2, Loss: 2.001255512237549
Epoch 3, Loss: 1.932166576385498
Epoch 4, Loss: 1.9314392805099487
Epoch 5, Loss: 1.9303874969482422
Epoch 6, Loss: 1.9289400577545166
Epoch 7, Loss: 1.9271104335784912
Epoch 8, Loss: 1.9250907897949219
Epoch 9, Loss: 1.9231288433074951
Epoch 10, Loss: 1.921002745628357
Epoch 11, Loss: 1.918537974357605
Epoch 1, Loss: 1.9506065845489502
Epoch 2, Loss: 2.024453639984131
Epoch 3, Loss: 2.019374132156372
Epoch 4, Loss: 1.8992021083831787
Epoch 5, Loss: 2.027941942214966
Epoch 6, Loss: 2.027926206588745
Epoch 7, Loss: 2.027909278869629
Epoch 8, Loss: 2.027890920639038
Epoch 9, Loss: 2.0278706550598145
Epoch 10, Loss: 2.027848243713379
Epoch 11, Loss: 2.0278239250183105
Epoch 1, Loss: 1.9636480808258057
Epoch 2, Loss: 1.962864875793457
Epoch 3, Loss: 1.961500644683838
Epoch 4, Loss: 1.9588837623596191
Epoch 5, Loss: 1.9534549713134766
Epoch 6, Loss: 1.9413398504257202
Epoch 7, Loss: 1.9171974658966064
Epoch 8, Loss: 1.892524

/var/folders/vt/hgv58_ws0rjfsg_1d8fcxgww0000gn/T/ipykernel_89077/1497090260.py:11: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.fc3(x))


In [757]:
labels.shape

torch.Size([31, 9])

In [758]:
from torchmetrics import Accuracy,Precision,Recall,ConfusionMatrix

In [759]:
cf = ConfusionMatrix(task = 'multiclass', num_classes=9)
acc = Accuracy(task = 'multiclass',num_classes=9)

In [760]:
model.eval()  # Set the model to evaluation mode
with torch.no_grad():  # Disable gradient calculation
    for feature, labels in training_data:
        output = model(feature.float())  # Forward pass
        # Evaluate your model, calculate accuracy, etc.
        pred = (output > 0.5).float()
    print(acc(pred,labels))
    print(cf(pred,labels)   )
    

tensor(0.7778)
tensor([[7, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]])


/var/folders/vt/hgv58_ws0rjfsg_1d8fcxgww0000gn/T/ipykernel_89077/1497090260.py:11: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.fc3(x))


In [761]:
from sklearn.metrics import classification_report

In [762]:
model.eval()  # Set model to evaluation mode
with torch.no_grad():  # Disable gradient calculation for evaluation
    for features, labels in training_data:
        output = model(features.float())
        
        # Apply softmax to get probabilities
        probs = F.softmax(output)
        
        # Get the index of the max probability (predicted class)
        pred = torch.argmax(probs)
        
        # You can now compare `pred` with your true labels for accuracy
        # Example:
        correct = (pred == labels).float().sum()

/var/folders/vt/hgv58_ws0rjfsg_1d8fcxgww0000gn/T/ipykernel_89077/1497090260.py:11: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.fc3(x))
/var/folders/vt/hgv58_ws0rjfsg_1d8fcxgww0000gn/T/ipykernel_89077/596041796.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probs = F.softmax(output)


In [764]:
labels

tensor([0, 0, 0, 0, 0, 1, 0, 0, 0])

In [763]:
probs

tensor([0.0933, 0.0933, 0.0933, 0.0933, 0.0933, 0.0933, 0.2536, 0.0933, 0.0933])