In [87]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer


In [88]:
parahagraph = """"Apple (company)" redirects here. For other companies with the same name, see Apple (disambiguation) § Businesses and organisations.
Apple Inc.

Logo since 1998

Apple Park is the company's headquarters in Cupertino, California, in Silicon Valley.
Formerly	
Apple Computer Company (1976–1977)
Apple Computer, Inc.
(1977–2007)
Company type	Public
Traded as	
Nasdaq: AAPL
Nasdaq-100 component
DJIA component
S&P 100 component
S&P 500 component
ISIN	US0378331005
Industry	
Consumer electronics
Software services
Online services
Founded	April 1, 1976; 48 years ago in Los Altos, California, U.S.
Founders	
Steve Jobs
Steve Wozniak
Ronald Wayne
Headquarters	1 Apple Park Way, Cupertino, California, U.S.
Number of locations	530 retail stores (2024)
Area served	Worldwide
Key people	
Arthur Levinson (Chairman)
Tim Cook (CEO)
Jeff Williams (COO)
Luca Maestri (CFO)
Products	
AirPods
Apple TV
Apple Watch
Apple Vision Pro
HomePod
iPad
iPhone
Macintosh
Full list
Services	
App Store
Apple Card
Apple One
Apple Music
Apple Pay
Apple TV+
iCloud
Shazam
Revenue	Decrease US$383.29 billion (2023)
Operating income	Decrease US$114.30 billion (2023)
Net income	Decrease US$97.00 billion (2023)
Total assets	Decrease US$352.58 billion (2023)
Total equity	Increase US$62.15 billion (2023)
Number of employees	161,000 (2023)
Subsidiaries	
Apple Studios
Beats Electronics
Beddit
Braeburn Capital
Claris
Drive.ai
InVisage Technologies
ASN	
714
Website	apple.com
Footnotes / references
[1][2][3][4][5]
Apple Inc. is an American multinational corporation and technology company headquartered in Cupertino, California, in Silicon Valley. It designs, develops, and sells consumer electronics, computer software, and online services. Devices include the iPhone, iPad, Mac, Apple Watch, Vision Pro, and Apple TV; operating systems include iOS, iPadOS, macOS, watchOS, tvOS, and visionOS; and software applications and services include iTunes, iCloud, Apple Music, and Apple TV+.

Since 2011, Apple has been the world's largest company by market capitalization except when Microsoft held the position between January and June 2024.[6][7][8] In 2022, Apple was the largest technology company by revenue, with US$394.3 billion.[9][failed verification] As of 2023, Apple was the fourth-largest personal computer vendor by unit sales,[10] the largest manufacturing company by revenue, and the largest vendor of mobile phones in the world.[11] It is one of the Big Five American information technology companies, alongside Alphabet (the parent company of Google), Amazon, Meta (the parent company of Facebook), and Microsoft.

Apple was founded as Apple Computer Company on April 1, 1976, to produce and market Steve Wozniak's Apple I personal computer. The company was incorporated by Wozniak and Steve Jobs in 1977. Its second computer, the Apple II, became a best seller as one of the first mass-produced microcomputers. Apple introduced the Lisa in 1983 and the Macintosh in 1984, as some of the first computers to use a graphical user interface and a mouse. By 1985, the company's internal problems included the high cost of its products and power struggles between executives. That year Jobs left Apple to form NeXT, Inc., and Wozniak withdrew to other ventures. The market for personal computers expanded and evolved throughout the 1990s, and Apple lost considerable market share to the lower-priced Wintel duopoly of the Microsoft Windows operating system on Intel-powered PC clones.

In 1997, Apple was weeks away from bankruptcy. To resolve its failed operating system strategy and entice Jobs's return, it bought NeXT. Over the next decade, Jobs guided Apple back to profitability through several tactics including introducing the iMac, iPod, iPhone, and iPad to critical acclaim, launching the "Think different" campaign and other memorable advertising campaigns, opening the Apple Store retail chain, and acquiring numerous companies to broaden its product portfolio. Jobs resigned in 2011 for health reasons, and died two months later. He was succeeded as CEO by Tim Cook.

Apple has received criticism regarding its contractors' labor practices, its environmental practices, and its business ethics, including anti-competitive practices and materials sourcing. Nevertheless, it has a large following and a high level of brand loyalty. It has been consistently ranked as one of the world's most valuable brands.

Apple became the first publicly traded U.S. company to be valued at over $1 trillion in August 2018, then at $2 trillion in August 2020, and at $3 trillion in January 2022. In June 2024, it was valued at just over $3.2 trillion.[8]"""

In [89]:
sentence_tokenized = nltk.sent_tokenize(parahagraph) 

In [90]:
corpus = []
for i in range (len(sentence_tokenized)):
    review = re.sub('[^a-zA-Z]', '  ', sentence_tokenized[i])
    review = review.lower()
    corpus.append(review)

## Stemmed Corpus

In [91]:
stemmer = PorterStemmer()

In [92]:
for i in range (len(corpus)):
    words_tokenized = nltk.word_tokenize(corpus[i])
    stemmed_corpus = [stemmer.stem(words) for words in words_tokenized if words not in (set(stopwords.words('english')))]
    corpus[i] = " ".join(stemmed_corpus)

In [93]:
corpus

['appl compani redirect',
 'compani name see appl disambigu busi organis',
 'appl inc',
 'logo sinc appl park compani headquart cupertino california silicon valley',
 'formerli appl comput compani appl comput inc compani type public trade nasdaq aapl nasdaq compon djia compon p compon p compon isin us industri consum electron softwar servic onlin servic found april year ago lo alto california u',
 'founder steve job steve wozniak ronald wayn headquart appl park way cupertino california u',
 'number locat retail store area serv worldwid key peopl arthur levinson chairman tim cook ceo jeff william coo luca maestri cfo product airpod appl tv appl watch appl vision pro homepod ipad iphon macintosh full list servic app store appl card appl one appl music appl pay appl tv icloud shazam revenu decreas us billion oper incom decreas us billion net incom decreas us billion total asset decreas us billion total equiti increas us billion number employe subsidiari appl studio beat electron beddit br

## Lemmatized Coprus

In [94]:
corpus2 = []
for i in range (len(sentence_tokenized)):
    review = re.sub('[^a-zA-Z]', '  ', sentence_tokenized[i])
    review = review.lower()
    corpus2.append(review)

In [95]:
corpus2

['  apple    company      redirects  here  ',
 'for  other  companies  with  the  same  name    see  apple    disambiguation        businesses  and  organisations  ',
 'apple  inc  ',
 'logo  since              apple  park  is  the  company  s  headquarters  in  cupertino    california    in  silicon  valley  ',
 'formerly    apple  computer  company                          apple  computer    inc                            company  type  public  traded  as    nasdaq    aapl  nasdaq          component  djia  component  s  p          component  s  p          component  isin  us                      industry    consumer  electronics  software  services  online  services  founded  april                          years  ago  in  los  altos    california    u  s  ',
 'founders    steve  jobs  steve  wozniak  ronald  wayne  headquarters      apple  park  way    cupertino    california    u  s  ',
 'number  of  locations          retail  stores                area  served  worldwide  key  peop

In [96]:
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/abhishekwaghchaure/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [97]:
for i in range (len(corpus2)):
    words_tokenized = nltk.word_tokenize(corpus[i])
    lemmatized_corpus = [lemmatizer.lemmatize(words) for words in words_tokenized if words not in set (stopwords.words('english'))]
    corpus2[i] = " ".join(lemmatized_corpus)

In [98]:
print(type(lemmatized_corpus))

<class 'list'>


In [99]:
print(type(corpus2))
corpus2

<class 'list'>


['appl compani redirect',
 'compani name see appl disambigu busi organis',
 'appl inc',
 'logo sinc appl park compani headquart cupertino california silicon valley',
 'formerli appl comput compani appl comput inc compani type public trade nasdaq aapl nasdaq compon djia compon p compon p compon isin u industri consum electron softwar servic onlin servic found april year ago lo alto california u',
 'founder steve job steve wozniak ronald wayn headquart appl park way cupertino california u',
 'number locat retail store area serv worldwid key peopl arthur levinson chairman tim cook ceo jeff william coo luca maestro cfo product airpod appl tv appl watch appl vision pro homepod ipad iphon macintosh full list servic app store appl card appl one appl music appl pay appl tv icloud shazam revenu decreas u billion oper incom decreas u billion net incom decreas u billion total asset decreas u billion total equiti increas u billion number employe subsidiari appl studio beat electron beddit braeburn

In [100]:
from sklearn.feature_extraction.text import CountVectorizer

In [101]:
cv = CountVectorizer(stop_words='english', lowercase=True, max_features=1500)

In [102]:
X = cv.fit_transform(corpus2).toarray()
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [120]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(corpus2).toarray()

In [121]:
print(type(X_tfidf))

<class 'numpy.ndarray'>


In [123]:
print(X_tfidf[3,])
len(X_tfidf[3])
print(X_tfidf.shape)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.14832    0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.2980876  0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.18343475
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.3213752  0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.3213752  0.         0.         0. 