In [6]:
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Embedding, Dense
from tensorflow.keras.utils import to_categorical,pad_sequences

In [7]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [8]:
stemmer = PorterStemmer()

In [9]:
corpus  = []
for i in range(len(docs)):
    review = re.sub('[^a-zA-z]',' ',docs[i])
    review = review.lower()
    corpus.append(review)
    word_tokenized = nltk.word_tokenize(corpus[i])
    stemmed_corpus = [stemmer.stem(word) for word in word_tokenized if word not in(set(stopwords.words('english')))]
    corpus[i] = " ".join(stemmed_corpus)

In [10]:
corpus

['recurr neural network',
 'neural network',
 'artifici neural',
 'connect node',
 'creat cycl',
 'allow output',
 'node affect subsequ',
 'exhibit tempor',
 'dynam behavior',
 'type neural network',
 'affect subsequ']

In [11]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
sequences =  tokenizer.texts_to_sequences(corpus)
X = pad_sequences(sequences, maxlen = max(len(seq) for seq in sequences))
print(X)

[[ 6  1  2]
 [ 0  1  2]
 [ 0  7  1]
 [ 0  8  3]
 [ 0  9 10]
 [ 0 11 12]
 [ 3  4  5]
 [ 0 13 14]
 [ 0 15 16]
 [17  1  2]
 [ 0  4  5]]


In [12]:
bag_of_words = CountVectorizer()
X_Bag_of_words = bag_of_words.fit_transform(corpus).toarray()
print(X_Bag_of_words)

[[0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]


In [15]:
Tfidf = TfidfVectorizer()
X_tfidf = Tfidf.fit_transform(corpus).toarray()
print(X_tfidf)
print(type(X_tfidf))

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.52938109 0.47309247 0.
  0.         0.70422949 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.74563614 0.66635332 0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.83008327 0.         0.         0.
  0.         0.         0.         0.         0.55763945 0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.76014955 0.
  0.         0.         0.         0.         0.         0.64974816
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.70710678
  0.70710678 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.70710678 0.         0.         0.         0.
  0.         0.         0.        