In [1]:
import torch

In [2]:
# device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
my_tensor1 = torch.tensor([[1,2,3],[4,5,6]],device='cpu')
print(my_tensor1)

tensor([[1, 2, 3],
        [4, 5, 6]])



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/envs/stable_env_nlp/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/stable_env_nlp/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/stable_env_nlp/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/envs/stable_env_nlp/lib/python3.10/site-packages/traitlets/config/application.py", line 10

In [4]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)

print(my_tensor)
print(my_tensor[0])
print(my_tensor.shape)
print(my_tensor.device)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1., 2., 3.])
torch.Size([2, 3])
cpu


In [5]:
x = torch.rand((3,3))
x = torch.eye(5,5)


In [6]:
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [7]:
x = torch.linspace(start = 0.05, end =1, steps = 10)
x = torch.zeros((3,3))
print(x)
torch.empty(size = (5,5)).normal_(mean = 0, std = 1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


tensor([[ 1.6176,  0.3273,  0.4470, -0.0216,  0.3393],
        [ 1.0394,  0.1650,  0.3308,  0.3003, -1.3930],
        [ 0.4751, -0.1962, -0.8457, -0.9112,  0.5127],
        [ 1.4767, -0.3106,  1.4494, -0.3885, -0.8741],
        [-0.2133, -0.3923,  0.4692, -1.3708, -0.8179]])

In [8]:
torch.empty(size = (15,10)).uniform_(0,1)

tensor([[0.0046, 0.1263, 0.8206, 0.1322, 0.1831, 0.8849, 0.6247, 0.2687, 0.9001,
         0.5125],
        [0.7864, 0.0315, 0.7216, 0.9928, 0.7956, 0.4836, 0.7655, 0.7954, 0.5450,
         0.9733],
        [0.4187, 0.0224, 0.9742, 0.2750, 0.1909, 0.6695, 0.1385, 0.3699, 0.6852,
         0.5806],
        [0.7597, 0.6150, 0.8297, 0.7259, 0.3331, 0.7075, 0.5737, 0.5329, 0.3474,
         0.0432],
        [0.2132, 0.0873, 0.8828, 0.7374, 0.2390, 0.5410, 0.0066, 0.3195, 0.7303,
         0.1292],
        [0.8989, 0.8898, 0.2100, 0.9596, 0.1927, 0.4401, 0.2602, 0.0757, 0.4380,
         0.0971],
        [0.9486, 0.5285, 0.0571, 0.0963, 0.7190, 0.3699, 0.7360, 0.7327, 0.3426,
         0.0733],
        [0.4182, 0.3096, 0.8583, 0.3597, 0.5946, 0.9829, 0.4675, 0.1847, 0.6938,
         0.8180],
        [0.3751, 0.9624, 0.8615, 0.2287, 0.9750, 0.7076, 0.6623, 0.5718, 0.5230,
         0.5336],
        [0.9895, 0.5940, 0.3770, 0.6484, 0.7386, 0.9514, 0.9891, 0.0619, 0.2785,
         0.4396],
        [0

In [9]:
torch.linspace(start=0.02,end=10,steps=3, dtype = torch.float32)

tensor([ 0.0200,  5.0100, 10.0000])

In [10]:
torch.arange(start=1,end=10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Converting tensors to different types

In [11]:
import numpy as np

array = np.zeros((5,5))

In [12]:
torch.from_numpy(array)

RuntimeError: Numpy is not available

In [14]:
tensor = torch.randn(3, 5, 7)
tensor2 = torch.randn(3,5)

In [16]:
print(type(tensor))
print(torch.dtype)

<class 'torch.Tensor'>
<class 'torch.dtype'>


In [17]:
print(tensor2)

tensor([[-2.6206,  1.0753, -0.3568,  0.7711,  1.5965],
        [ 0.3307, -0.6471,  0.5818, -0.3293, -0.4117],
        [-0.6212,  0.5400, -1.0890,  1.8086,  0.8381]])


In [27]:
print(tensor.shape)
print(tensor.numel())

torch.Size([3, 5, 7])
105


In [13]:
tensor = [[1,2,3],[1,2,3],[4,5,6],[4,5,6]]

In [23]:
print(type(tensor))
real_tensor =torch.tensor(tensor, dtype=torch.float64)
print(real_tensor)
print(real_tensor.dtype)
print(type(real_tensor))
print(real_tensor.shape)

<class 'list'>
tensor([[1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float64
<class 'torch.Tensor'>
torch.Size([4, 3])


In [52]:
torch.rand_like(real_tensor)

tensor([[0.4101, 0.2752, 0.8823],
        [0.7056, 0.5537, 0.4521],
        [0.5061, 0.1842, 0.9900],
        [0.5962, 0.7901, 0.2643]], dtype=torch.float64)

In [53]:
torch.empty_like(real_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [24]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
identity_matrix = torch.eye(5, dtype = torch.int64)
print(identity_matrix)
print(type(identity_matrix))

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])
<class 'torch.Tensor'>


In [35]:
torch.linspace(0,100,15,dtype=torch.int16)

tensor([  0,   7,  14,  21,  28,  35,  42,  50,  57,  64,  71,  78,  85,  92,
        100], dtype=torch.int16)

In [46]:
square_matrix = torch.full((3,3),6)
print(square_matrix)

identity_matrix = torch.eye(5, dtype=torch.int)
print(identity_matrix)

vector = torch.arange(0,10,1)
print(vector)

vector2 =torch.linspace(0,1,10)
print(vector2)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int32)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [51]:
empty_matrix = torch.zeros(3,3)
print(empty_matrix)

random_matrix = torch.randn(2,3)
print(random_matrix)

random_2 = torch.rand(2,3)
print(random_2)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[-1.3708,  0.3068, -0.2712],
        [ 1.3652, -1.0240,  0.9374]])
tensor([[0.4045, 0.1973, 0.7069],
        [0.3468, 0.0087, 0.9110]])


In [64]:
torch.manual_seed(100)
x = torch.rand(3,3)
print(x)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])


### Scalar Operations

In [59]:
## addition
add = x + 2
print(add)

sub = x - 2
print(sub)

multiply = x * 3
print(multiply)

tensor([[2.3221, 2.9215, 2.2711],
        [2.6352, 2.4454, 2.2248],
        [2.7026, 2.6572, 2.6469]])
tensor([[-1.6779, -1.0785, -1.7289],
        [-1.3648, -1.5546, -1.7752],
        [-1.2974, -1.3428, -1.3531]])
tensor([[0.9662, 2.7646, 0.8134],
        [1.9055, 1.3362, 0.6744],
        [2.1078, 1.9716, 1.9408]])


## Elementwise Operations

In [74]:
torch.manual_seed(100)
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x)
print(y)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])
tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])


In [77]:

print(x + y)
print(x-y)
print(x*y)
print(x/y)
print(x % y)

tensor([[0.2297, 0.9375, 0.9982],
        [1.1956, 1.4641, 1.1722],
        [1.1641, 1.0397, 0.9645]])
tensor([[-0.0064,  0.6941, -0.4730],
        [-0.2279, -0.1111,  0.3356],
        [-0.6387, -0.9540, -0.5485]])
tensor([[0.0132, 0.0993, 0.1931],
        [0.3444, 0.5328, 0.3154],
        [0.2368, 0.0427, 0.1574]])
tensor([[0.9460, 6.7040, 0.3569],
        [0.6798, 0.8590, 1.8023],
        [0.2914, 0.0430, 0.2750]])
tensor([[0.1117, 0.0857, 0.2626],
        [0.4839, 0.6765, 0.3356],
        [0.2627, 0.0428, 0.2080]])


## Reduction operations


In [92]:
e = torch.randint(size = (2,3) , low = 0, high = 10, dtype = torch.float32)
print(e)

tensor([[7., 0., 0.],
        [9., 5., 7.]])


In [93]:
print(torch.sum(e))
print(torch.sum(e, dim = 0))
print(torch.sum(e, dim = 1))

tensor(28.)
tensor([16.,  5.,  7.])
tensor([ 7., 21.])


In [95]:
print(torch.mean(e))
print(torch.mean(e, dim = 0))

tensor(4.6667)
tensor([8.0000, 2.5000, 3.5000])


In [100]:
print(torch.median(e))
print(torch.max(e))
print(torch.prod(e))
print(torch.var(e))

tensor(5.)
tensor(9.)
tensor(0.)
tensor(14.6667)


In [102]:
print(torch.argmax(e))
print(torch.argmin(e))

tensor(3)
tensor(1)


## Matrix Operations

In [103]:
torch.manual_seed(100)
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x)
print(y)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])
tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])


In [122]:
print(torch.matmul(x,y))

tensor([[0.8305, 0.9179, 0.6220],
        [1.2182, 1.3432, 1.2093],
        [0.2490, 0.2731, 0.3685]])


In [141]:
vector = torch.linspace(0,1,3).unsqueeze(1)
print(vector)
vector.shape

tensor([[0.0000],
        [0.5000],
        [1.0000]])


torch.Size([3, 1])

In [143]:
transformed = torch.mm(x,vector)
print(transformed)

tensor([[0.6705],
        [1.0922],
        [0.2294]])


In [144]:
torch.det(x)

tensor(0.0503)

In [145]:
inverse = torch.inverse(x)
print(inverse)

tensor([[ 2.1540, -3.1479,  8.6896],
        [ 1.9345, -0.9087,  0.8514],
        [-3.1183,  4.1622, -6.3412]])


In [146]:
ori_x = torch.mm(inverse, transformed)
print(ori_x)

tensor([[0.0000],
        [0.5000],
        [1.0000]])
