In [2]:
import torch

In [3]:
# device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [4]:
my_tensor1 = torch.tensor([[1,2,3],[4,5,6]],device='cpu')
print(my_tensor1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)

print(my_tensor)
print(my_tensor[0])
print(my_tensor.shape)
print(my_tensor.device)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1., 2., 3.])
torch.Size([2, 3])
cpu


In [6]:
x = torch.rand((3,3))
x = torch.eye(5,5)


In [7]:
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [8]:
x = torch.linspace(start = 0.05, end =1, steps = 10)
x = torch.zeros((3,3))
print(x)
torch.empty(size = (5,5)).normal_(mean = 0, std = 1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


tensor([[-0.3558,  0.7379, -1.7216, -0.3631,  1.1865],
        [ 0.4218, -0.4094,  0.5986,  0.1697,  0.2632],
        [-0.0799, -0.0855, -0.3329, -0.7650, -1.4052],
        [ 2.5321, -0.4126,  0.8638, -0.3430, -1.0707],
        [-1.0863,  0.6351,  1.0240, -0.0723,  1.3903]])

In [9]:
torch.empty(size = (15,10)).uniform_(0,1)

tensor([[4.5904e-01, 6.8572e-01, 5.6569e-01, 9.1080e-01, 7.5640e-01, 3.4257e-01,
         3.8202e-01, 8.4676e-01, 7.8185e-01, 8.0855e-01],
        [4.7160e-01, 1.4901e-01, 7.7415e-01, 4.8595e-02, 6.3844e-01, 9.9028e-01,
         1.5187e-02, 4.2667e-01, 6.6851e-01, 2.9709e-01],
        [3.5013e-01, 1.5020e-01, 7.1725e-01, 8.8221e-01, 8.8149e-01, 7.6207e-02,
         2.1494e-03, 8.2127e-01, 1.5041e-01, 2.9187e-01],
        [2.5760e-01, 4.3073e-02, 9.8494e-01, 7.8187e-02, 3.7318e-01, 5.4223e-01,
         4.5217e-01, 9.1778e-01, 9.5354e-01, 6.4314e-01],
        [6.6348e-01, 2.3656e-01, 5.5589e-01, 4.0179e-01, 9.0418e-01, 9.3163e-01,
         5.9255e-01, 3.5495e-01, 3.6582e-01, 7.1666e-01],
        [2.8658e-04, 5.7095e-01, 1.0425e-02, 7.5228e-01, 3.5393e-02, 1.5242e-02,
         7.4262e-01, 9.4087e-01, 8.9348e-01, 4.9843e-01],
        [8.9688e-01, 5.5702e-01, 7.6240e-01, 9.9075e-01, 8.7107e-01, 7.6973e-01,
         6.6710e-01, 6.5159e-01, 6.9165e-02, 1.7564e-01],
        [3.5276e-01, 3.4051

In [10]:
torch.linspace(start=0.02,end=10,steps=3, dtype = torch.float32)

tensor([ 0.0200,  5.0100, 10.0000])

In [11]:
torch.arange(start=1,end=10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Converting tensors to different types

In [12]:
import numpy as np

array = np.zeros((5,5))

In [13]:
torch.from_numpy(array)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [16]:
tensor = torch.randn(3, 5, 7)
tensor2 = torch.randn(3,5)

In [15]:
tensor

tensor([[[ 0.6567, -1.2895,  1.9252, -0.3503,  0.2045,  0.9494, -0.0080],
         [ 1.0024, -1.0137,  0.7811,  0.3498, -1.6366, -0.8023, -0.3725],
         [ 0.9333, -1.3199,  0.1279, -0.8405,  1.4475, -1.5913,  0.3452],
         [-0.0261, -0.1443, -1.6655, -0.8761, -0.9584, -0.8526,  0.1086],
         [ 0.5762,  0.9218, -0.4195, -0.9456,  0.2614, -0.0459, -1.7869]],

        [[-0.0331,  1.3913, -0.2608,  0.4408, -0.8804,  0.2045, -0.2662],
         [-0.9797,  1.1224, -0.8129,  0.4757,  0.9840,  0.1403,  1.2394],
         [ 0.1604,  1.0113, -0.5701, -0.0397, -0.3808,  0.1814, -0.5136],
         [ 1.7745,  1.3186,  0.6035, -0.0186,  1.7702, -0.2886, -0.2118],
         [-2.3470,  0.8636, -0.2389,  0.0915,  0.0733, -0.4188, -0.1687]],

        [[-0.7038,  1.1333, -0.2897, -1.3056,  1.0121,  2.1352, -1.1139],
         [-2.1006, -1.0298, -0.1093, -0.6660,  0.5843, -0.0272,  1.5453],
         [ 1.2059,  0.8602,  1.1104, -1.5080, -1.0279, -1.0576,  0.4540],
         [ 0.6408,  0.2916, -0.910

In [17]:
print(tensor2)

tensor([[-2.6206,  1.0753, -0.3568,  0.7711,  1.5965],
        [ 0.3307, -0.6471,  0.5818, -0.3293, -0.4117],
        [-0.6212,  0.5400, -1.0890,  1.8086,  0.8381]])


In [27]:
print(tensor.shape)
print(tensor.numel())

torch.Size([3, 5, 7])
105
