In [7]:
import torch
import sys

In [14]:
device = torch.device('mps')

In [16]:
my_tensor = torch.tensor([[1,2,3,4],[5,6,7,8]], dtype = torch.float32, device = device, requires_grad=True)
print(my_tensor)
print(sys.getsizeof(my_tensor))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], device='mps:0', requires_grad=True)
72


In [20]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

torch.float32
mps:0
torch.Size([2, 4])
True


## Initialization Methods

In [30]:
print(torch.empty(size= (3,3))) # ----> Empty matrix
print(torch.zeros(3,3)) # ----> null matrix
print(torch.rand(3,3)) # ----> uniform distribution
print(torch.eye(3,3)) # ----> Identity Matrix
print(torch.ones(2,2)) # ---> One matrix
print(torch.arange(start = 0, end = 10, step=1))
print(torch.linspace(start=0.1, end =1, steps= 10))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.7036, 0.8627, 0.7471],
        [0.5713, 0.4864, 0.2822],
        [0.4020, 0.7848, 0.1218]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [38]:
print(torch.empty(size = (3,3)).normal_(mean=0, std =1))
print(torch.diag(torch.ones(3,3)))

tensor([[ 1.0788,  1.2590,  0.2829],
        [-0.0550,  0.2846, -1.6366],
        [-0.1273, -1.3923, -0.9740]])
tensor([1., 1., 1.])


## How to initialize and convert tensors to other datatypes(int, float, double)

In [47]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [50]:
import numpy as np
np_arr = np.zeros(3)
print(np_arr)
tensor = torch.from_numpy(np_arr)
print(tensor)
print(tensor.numpy())

[0. 0. 0.]
tensor([0., 0., 0.], dtype=torch.float64)
[0. 0. 0.]


## Tensor Math Operations

In [65]:
x = torch.tensor([1,2,3])
y = torch.tensor([5,6,8])

print(x+y)
print(x-y)
print(x/y)
print(x//y)

z1 = torch.zeros(3)
torch.add(x, y, out=z1)
print(z1)

print(torch.sub(x,y))

## inplace operations
t = torch.zeros(3)
print(t.add_(x))

## exponentiation
z = x.pow(2)
print(z)

## Simple comparison
print(x > 0)


tensor([ 6,  8, 11])
tensor([-4, -4, -5])
tensor([0.2000, 0.3333, 0.3750])
tensor([0, 0, 0])
tensor([ 6.,  8., 11.])
tensor([-4, -4, -5])
tensor([1., 2., 3.])
tensor([1, 4, 9])
tensor([True, True, True])


In [87]:
x1 = torch.rand(3,5)
x2 = torch.rand(5,3)

print(x1)
print(x2)

tensor([[0.4116, 0.7902, 0.5559, 0.4454, 0.6366],
        [0.0227, 0.1829, 0.3479, 0.6470, 0.5356],
        [0.8845, 0.6696, 0.5990, 0.1782, 0.2934]])
tensor([[0.4218, 0.4260, 0.8899],
        [0.9346, 0.0503, 0.3193],
        [0.4849, 0.9074, 0.6105],
        [0.7263, 0.9807, 0.3105],
        [0.0773, 0.8664, 0.5121]])


In [89]:
## multiplication
print(torch.mm(x1,x2))
print(x1.mm(x2))

tensor([[1.5545, 1.7079, 1.4223],
        [0.8605, 1.4331, 0.7662],
        [1.4415, 1.3830, 1.5723]])
tensor([[1.5545, 1.7079, 1.4223],
        [0.8605, 1.4331, 0.7662],
        [1.4415, 1.3830, 1.5723]])


In [96]:
print(torch.matmul(x1,x2))
print(x1.matmul(x2))

tensor([[1.5545, 1.7079, 1.4223],
        [0.8605, 1.4331, 0.7662],
        [1.4415, 1.3830, 1.5723]])
tensor([[1.5545, 1.7079, 1.4223],
        [0.8605, 1.4331, 0.7662],
        [1.4415, 1.3830, 1.5723]])


In [94]:
## matrix exponentiation
matrix_exp = torch.rand(3,3)
matrix_exp.matrix_power(2)

tensor([[0.1162, 0.0683, 0.0714],
        [0.4414, 0.2778, 0.2748],
        [0.7009, 0.3893, 0.4286]])

In [101]:
## elementwise multiplication
x = torch.rand(3,3)
y = torch.eye(3,3)
print(x)
print(y)

print(f'Matrix multiplication : {torch.matmul(x,y)}')
print(f'Elementwise multiplication : {x*y}')

tensor([[0.1281, 0.2709, 0.9139],
        [0.9911, 0.5670, 0.1999],
        [0.5289, 0.4282, 0.4788]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Matrix multiplication : tensor([[0.1281, 0.2709, 0.9139],
        [0.9911, 0.5670, 0.1999],
        [0.5289, 0.4282, 0.4788]])
Elementwise multiplication : tensor([[0.1281, 0.0000, 0.0000],
        [0.0000, 0.5670, 0.0000],
        [0.0000, 0.0000, 0.4788]])


In [107]:
vector1 = torch.linspace(start = 0, end = 10, steps = 10)
vector2 = torch.linspace(start = 0, end = 20, steps = 10)
print(vector1)
print(vector2)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])


In [111]:
print(vector1 * vector2)
print(vector1.matmul(vector2)) # ----> should expect scalar as 2 vectors multiplied gives us a scalar
print(vector1.dot(vector2))

tensor([  0.0000,   2.4691,   9.8765,  22.2222,  39.5062,  61.7284,  88.8889,
        120.9876, 158.0247, 200.0000])
tensor(703.7037)
tensor(703.7037)


In [116]:
## Example of broadcasting --->> basically multiply/add/subtract elementwise a matrix with a vector

x1 = torch.rand(5,5)
x2 = torch.rand(1,5)
print(x1)
print(x2)


tensor([[0.0853, 0.3702, 0.7917, 0.9340, 0.0846],
        [0.2362, 0.5478, 0.4497, 0.2507, 0.5951],
        [0.7193, 0.4344, 0.9337, 0.0324, 0.1078],
        [0.9315, 0.1702, 0.6185, 0.6582, 0.4423],
        [0.2039, 0.9812, 0.8342, 0.4612, 0.5950]])
tensor([[0.4640, 0.8180, 0.8708, 0.9022, 0.7142]])


In [130]:
print(x1.shape)
print(x2.shape)
print(x2.squeeze(1).shape)

torch.Size([5, 5])
torch.Size([1, 5])
torch.Size([1, 5])


In [131]:
print(x1 - x2)
print(x1.mul(x2))
print(x2.matmul(x1))



tensor([[-0.3787, -0.4478, -0.0791,  0.0318, -0.6296],
        [-0.2279, -0.2702, -0.4211, -0.6515, -0.1191],
        [ 0.2553, -0.3836,  0.0629, -0.8698, -0.6064],
        [ 0.4675, -0.6477, -0.2523, -0.2440, -0.2718],
        [-0.2601,  0.1632, -0.0366, -0.4410, -0.1191]])
tensor([[0.0396, 0.3028, 0.6894, 0.8427, 0.0604],
        [0.1096, 0.4481, 0.3916, 0.2261, 0.4250],
        [0.3338, 0.3553, 0.8131, 0.0292, 0.0770],
        [0.4322, 0.1393, 0.5386, 0.5938, 0.3159],
        [0.0946, 0.8026, 0.7264, 0.4161, 0.4249]])
tensor([[1.8452, 1.8524, 2.7021, 1.5898, 1.4439]])


In [141]:
x = torch.tensor([[1,2,3,4], [2,4,6,8]]) ## Shape = (2,4)
print(x.shape)
print(torch.max(x, dim = 0))
print(torch.max(x, dim = 1))

torch.Size([2, 4])
torch.return_types.max(
values=tensor([2, 4, 6, 8]),
indices=tensor([1, 1, 1, 1]))
torch.return_types.max(
values=tensor([4, 8]),
indices=tensor([3, 3]))


## Indexing in Tensors

In [143]:
batch_size = 32
features = 25

x = torch.rand(batch_size, features)

In [152]:
print(x[0]) ##----> the row at 0 indes and all the colms
print(x[:,0]) ## ---> the column at 0 index ad all the rows init

tensor([0.9982, 0.0857, 0.0071, 0.2569, 0.8349, 0.9560, 0.3892, 0.9739, 0.3523,
        0.3468, 0.3128, 0.9625, 0.9309, 0.4454, 0.9609, 0.4858, 0.2609, 0.0626,
        0.3426, 0.3011, 0.8428, 0.3906, 0.6870, 0.6716, 0.8140])
tensor([0.9982, 0.9040, 0.4806, 0.8180, 0.0033, 0.7535, 0.9386, 0.7949, 0.5364,
        0.0092, 0.1194, 0.6075, 0.0878, 0.8964, 0.2069, 0.5512, 0.3039, 0.3025,
        0.1248, 0.0243, 0.4153, 0.1746, 0.2650, 0.5631, 0.2957, 0.5626, 0.5079,
        0.1703, 0.2933, 0.6724, 0.0347, 0.5196])


In [155]:
print(x[2])

tensor([0.4806, 0.8169, 0.4015, 0.7238, 0.1794, 0.7192, 0.2743, 0.8973, 0.8209,
        0.3696, 0.0982, 0.1771, 0.5541, 0.0202, 0.6720, 0.6887, 0.6452, 0.9426,
        0.9342, 0.1186, 0.6455, 0.1025, 0.2508, 0.6521, 0.7161])


In [153]:
print(x[2, 0:10])

tensor([0.4806, 0.8169, 0.4015, 0.7238, 0.1794, 0.7192, 0.2743, 0.8973, 0.8209,
        0.3696])


## Tensor Reshaping

In [170]:
y = torch.arange(9)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [171]:
y_3X3 = y.reshape(3,3)
print(y_3X3)

y_3X3_view = y.view(3,3)
print(y_3X3_view)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [172]:
x = y_3X3_view.t()
print(x)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [173]:
x1 = torch.rand((2,5))
x2 = torch.rand(2,5)
print(x1)
print(x2)

tensor([[0.0260, 0.9423, 0.5785, 0.9344, 0.3229],
        [0.2276, 0.1958, 0.3654, 0.7044, 0.7294]])
tensor([[0.3969, 0.3747, 0.2195, 0.1473, 0.0552],
        [0.7470, 0.7525, 0.3223, 0.4320, 0.1553]])


In [177]:
print(torch.concat((x1,x2),dim = 0).shape)
print(torch.concat((x1,x2), dim = 1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [185]:
## Flatening 
batch = 50
rows = 100
cols = 100

data = torch.rand(batch, rows, cols)
print(data.shape)
print(data.view(batch, -1).shape)

torch.Size([50, 100, 100])
torch.Size([50, 10000])


In [186]:
data_2 = torch.rand(batch,rows, cols)
print(data_2.shape)

torch.Size([50, 100, 100])


In [188]:
data_2.permute(1,2,0).shape

torch.Size([100, 100, 50])

In [200]:
## Squeeze and unsqueeze

x = torch.arange(10)
print(x.shape)

## Add an extra dimension to the left of x or right of x
print(x.unsqueeze(1).shape)
print(x.unsqueeze(0).shape)

## Remove an extra dimension from x
print(x.squeeze(0).shape)

torch.Size([10])
torch.Size([10, 1])
torch.Size([1, 10])
torch.Size([10])
